export type ErrorCodes =
  | "InvalidCreds"
  | "Unauthenticated"
  | "InvalidToken"
  | "UserAlreadyExists"
  | "ComponentNotFound"
  | "CountryNotFound"
  | "CurrencyNotFound"
  | "ValidationFailed"
  | "NoGoogleLinked"
  | "GoogleFailed"
  | "ReceiptNotFound"
  | "NameAlreadyExists"
  | "FailedDeletion"
  | "UserDoesntExist"
  | "GenericError"
  | "NotFound"
  | "INVALID";
